name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [21]  # or the Node.js version you're using
        os: ["ubuntu-22.04"]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: |
        cd frontend
        npm install

    - name: Build
      run: |
        cd frontend
        npm run build

    - name: Install Backend Dependencies
      run: npm install

    - name: Set Environment Variables
      run: echo "${{secrets.CHATAPP}}" > backend/.env

    - name: Restart PM2
      run: pm2 restart index
